version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com

      - echo Setting up Python 3.11...
      - python3.11 --version

      - echo Installing dependencies...
      - pip install -r services/search/requirements.txt

  build:
    commands:
      - echo Build started on `date`

      - echo Running tests...
      - PYTHONPATH=services/search/src pytest services/search/tests/ -v --tb=short

      - echo Building Docker image...
      - docker build -t travelhub-search services/search/
      - docker tag travelhub-search:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/travelhub-search:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/travelhub-search:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"search","imageUri":"%s.dkr.ecr.us-east-1.amazonaws.com/travelhub-search:latest"}]' $AWS_ACCOUNT_ID > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
